    LIST P=18F4550
    INCLUDE "P18F4550.INC"
	    ORG 0X00 
	    MOVLW   0X0F
	    MOVWF   ADCON1 
	    MOVLW   0X07
	    MOVWF   CMCON 
	    MOVLW   0XFF
	    MOVWF   OSCCON 
	    SETF    TRISB 
	    CLRF    TRISA
INICIO	    BCF	    LATA,RA0
	    BCF	    LATA,RA1
	    MOVLW   0X00
	    CPFSEQ  PORTB
	    GOTO    UNO
	    GOTO    AMARILLO
UNO	    MOVLW   0X01
	    CPFSEQ  PORTB
	    GOTO    DOS
	    GOTO    AMARILLO
DOS	    MOVLW   0X02
	    CPFSEQ  PORTB
	    GOTO    TRES
	    GOTO    AMARILLO
TRES	    MOVLW   0X03
	    CPFSEQ  PORTB
	    GOTO    CUATRO
	    GOTO    AZUL
CUATRO	    MOVLW   0X04
	    CPFSEQ  PORTB
	    GOTO    CINCO
	    GOTO    AMARILLO	 
CINCO	    MOVLW   0X05
	    CPFSEQ  PORTB
	    GOTO    SEIS
	    GOTO    AZUL
SEIS	    MOVLW   0X06
	    CPFSEQ  PORTB
	    GOTO    SIETE
	    GOTO    AZUL
SIETE	    MOVLW   0X07
	    CPFSEQ  PORTB
	    GOTO    OCHO
	    GOTO    APAGAR
OCHO	    MOVLW   0X08
	    CPFSEQ  PORTB
	    GOTO    NUEVE
	    GOTO    AMARILLO
NUEVE	    MOVLW   0X09
	    CPFSEQ  PORTB
	    GOTO    DIEZ
	    GOTO    AMARILLO
DIEZ	    MOVLW   0X0A
	    CPFSEQ  PORTB
	    GOTO    ONCE
	    GOTO    AZUL
ONCE	    MOVLW   0X0B
	    CPFSEQ  PORTB
	    GOTO    DOCE
	    GOTO    APAGAR
DOCE	    MOVLW   0X0C
	    CPFSEQ  PORTB
	    GOTO    TRECE
	    GOTO    AMARILLO
TRECE	    MOVLW   0X0D
	    CPFSEQ  PORTB
	    GOTO    CATORCE
	    GOTO    APAGAR
CATORCE	    MOVLW   0X0E
	    CPFSEQ  PORTB
	    GOTO    QUINCE
	    GOTO    APAGAR
QUINCE	    MOVLW   0X0F
	    CPFSEQ  PORTB
	    GOTO    APAGAR
	    GOTO    APAGAR	    		
AMARILLO    BSF	    LATA,RA0
	    GOTO    INICIO
AZUL	    BSF	    LATA,RA1
	    GOTO    INICIO
APAGAR	    BCF	    LATA,RA0
	    BCF	    LATA,RA1
	    GOTO    INICIO
	    END