	        LIST P = 18F4550
	        INCLUDE "P18F4550.INC"
		;ESTE BLOQUE ES PARA EL OSCILADOR EXTERNO SE COMENTA PORQUE NO LO USAMOS		
		;CONFIG1L dir 300000h 	
		;CONFIG	PLLDIV=5	  
		;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
		;CONFIG	USBDIV=1

		;CONFIG1H dir 300001h	
		CONFIG	FOSC = INTOSCIO_EC  ;OSCILADOR INTERNO, RA6 COMO PIN E/S, USB USA OSC EC
		CONFIG	FCMEN=OFF           ;DESHABILITADO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF
		;CONFIG2L DIR 300002H	
		CONFIG	PWRT=ON          ;PWRT HABILITADO
		CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
		CONFIG  BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=OFF	 ;REGULADOR DE USB APAGADO
		;CONFIG2H DIR 300003H	
		CONFIG	WDT=OFF          ;WATCH DOG DESHABILITADO
		CONFIG  WDTPS=32768      ;TIMER DEL WATCHDOG 
		;CONFIG3H DIR 300005H	
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 E/S DIGITALES
		CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIGURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO
		;CONFIG4L DIR 300006H	
		CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE DESACTIVADO PARA USAR PIN RB5 E/S
		CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF        ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO
		;CONFIG5L DIR 300008H	
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		;CONFIG5H DR 300009H	
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM NO PROTEGIDA
		;CONFIG6L DIR 30000AH	
		CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	
		CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEABLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 ;EEPROM DE DATOS NO PROTEGIDA

		;CONFIG7L DIR 30000CH	
		CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH	
		CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS

		ORG 0x00
		MOVLW	0x0F	;ENTRADAS/SALIDAS DIGITALES EN ALGUNOS PINES DE LOS PUERTOS PA,PB,PE
		MOVWF	ADCON1
		MOVLW	0x07	;DESHABILITAR COMPARADORES EN LOS PINES RA0,RA1,RA2,RA3
		MOVWF	CMCON
		MOVLW	0xFF	;OSCILADOR INTERNO DE 8 MHZ
		MOVWF	OSCCON
		BCF	UCON,USBEN ;HABILITAMOS RC5 Y RC4 COMO ENTRADAS DIGITALES Y NO SE CONFIGURAN CON TRISC
		END
    ; palabra de configuracion
#DEFINE ENTA RB0 ;DEFINIMOS ENTRADAS Y SALIDAS EN EL PUERTO B
#DEFINE ENTB RB1
#DEFINE ENTC RB2
#DEFINE ENTD RB3
#DEFINE SALW RB4
#DEFINE SALX RB5
#DEFINE SALY RB6
#DEFINE SALZ RB7
	    ORG 0X00 ;INICIA EN ESE REGISTRO DE MEMORIA
	    MOVLW   0X0F
	    MOVWF   ADCON1 ;EL ADCON INDICA QUE NUESTRAS ENTRADAS SON DIGITALES
	    MOVLW   0X07
	    MOVWF   CMCON ;ESPECIFICA UNA FRECUENCIA INTERNA DE 8Mhz
	    MOVLW   0XFF
	    MOVWF   OSCCON ;SE DESHABILITAN LOS COMPARADORES
	    BSF	    TRISB, ENTA ;CONFIGURAMOS EL PUERTO A PARA ENTRADAS Y SALIDAS INICIANDO TODAS EN 0
	    BSF	    TRISB, ENTB
	    BSF	    TRISB, ENTC
	    BSF	    TRISB, ENTD
	    BCF	    TRISB, SALW
	    BCF	    TRISB, SALX
	    BCF	    TRISB, SALY
	    BCF	    TRISB, SALZ
INICIO	    BTFSC   PORTB, ENTA ;PREGUNTA POR A
	    GOTO    SIGB
	    BTFSC   PORTB,ENTB	;SI A=0 SE PREGUNTA POR B
	    GOTO    OTROC
	    BTFSC   PORTB,ENTC	;SI B=0 SE PREGUNTA POR C
	    GOTO    OTROD3
	    BTFSC   PORTB,ENTD	;SI C=0 SE PREGUNTA POR D
	    GOTO    ENCWX
	    GOTO    INICIO  
SIGB	    BSF	    LATB,SALW ;SE ENCIENDEN LAS ALARMAS Y SE PREGUNTA POR B
	    BSF	    LATB,SALX
	    BTFSC   PORTB,ENTB ;SE PREGUNTA POR B
	    GOTO    SIGC1    ;SI B=1 IR A SIGC1
	    GOTO    SIGC2   ;SI B=0 IR A SIGC2	    
SIGC1	    BTFSC   PORTB,ENTC	;SE PREGUNTA POR C
	    GOTO    ENCTODO
	    GOTO    SIGD1
SIGC2	    BTFSC   PORTB,ENTC	;SE PREGUNTA POR C
	    GOTO    SIGD2   ;SI ES C=1 VA A SIGD2
	    GOTO    SIGD3
SIGD1	    BTFSC   PORTB,ENTD ;PREGUNTA POR D
	    GOTO    ENCTODO
	    GOTO    FINALIZAR
SIGD2	    BSF	    LATB,SALY	;SE ENCIENDE LA SIRENA
	    BTFSC   PORTB,ENTD
	    BSF	    LATB,SALZ	;SI D=1 SE LLAMA
	    GOTO    INICIO  ;SI D=0 SE VA AL INICIO
SIGD3	    BTFSC   PORTB,ENTD	;SE PREGUNTA POR D
	    BSF	    LATB,SALY ;SI D=1 SE ENCIENDE SIRENA
	    GOTO    INICIO  ;SINO SE VA A INICIO	    
ENCTODO	    BSF	    LATB,SALY
	    BSF	    LATB,SALZ
	    GOTO    INICIO	    
FINALIZAR   BCF	    LATB,SALY
	    BCF	    LATB,SALZ
	    GOTO    INICIO
OTROC	    BSF	    LATB,SALW	;SE ENCIENDEN LAS ALARMAS Y SE PREGUNTA POR C
	    BSF	    LATB,SALX
	    BTFSC   PORTB,ENTC
	    GOTO    OTROD1
	    GOTO    OTROD2    
OTROD1	    BSF	    LATB,SALY	;SE ENCIENDE SIRENA
	    BTFSC   PORTB,ENTD	;SE PREGUNTA POR D
	    BSF	    LATB,SALZ	;SI D=1 SE LLAMA
	    GOTO    INICIO	;SINO SE VA A INICIO
OTROD2	    BTFSC   PORTB,ENTD
	    BSF	    LATB,SALY
	    GOTO    INICIO
OTROD3 	    BSF	    LATB,SALW
	    BSF	    LATB,SALX
	    GOTO    INICIO
ENCWX	    BSF	    LATB,SALW	;SE ENCIENDEN LAS ALARMAS Y SE VA A INICIO
	    BSF	    LATB,SALX
	    GOTO    INICIO
		    END
	



