    LIST P=18F4550
    INCLUDE "P18F4550.INC"
	    ORG 0X00 
	    MOVLW   0X0F
	    MOVWF   ADCON1 ;ENTRADAS DIGITALES
	    MOVLW   0X07
	    MOVWF   CMCON 
	    MOVLW   0XFF
	    MOVWF   OSCCON 
	    MOVLW   0XFF
	    MOVWF   TRISB ;TRISB CONFIGURADO COMO ENTRADA
	    MOVLW   0X00
	    MOVWF   TRISC ;TRISC COMO SALIDAS	    
INICIO	    MOVLW   0X00    
	    CPFSEQ  PORTB    
	    GOTO    UNO	    
	    GOTO    REPROBADO
UNO	    MOVLW   0X01
	    CPFSEQ  PORTB
	    GOTO    DOS
	    GOTO    REPROBADO
DOS	    MOVLW   0X02
	    CPFSEQ  PORTB
	    GOTO    TRES
	    GOTO    REPROBADO
TRES	    MOVLW   0X03
	    CPFSEQ  PORTB
	    GOTO    CUATRO
	    GOTO    REPETIR
CUATRO	    MOVLW   0X04
	    CPFSEQ  PORTB
	    GOTO    CINCO
	    GOTO    REPROBADO	 
CINCO	    MOVLW   0X05
	    CPFSEQ  PORTB
	    GOTO    SEIS
	    GOTO    REPETIR
SEIS	    MOVLW   0X06
	    CPFSEQ  PORTB
	    GOTO    SIETE
	    GOTO    REPETIR
SIETE	    MOVLW   0X07
	    CPFSEQ  PORTB
	    GOTO    OCHO
	    GOTO    APROBADO
OCHO	    MOVLW   0X08
	    CPFSEQ  PORTB
	    GOTO    NUEVE
	    GOTO    REPROBADO
NUEVE	    MOVLW   0X09
	    CPFSEQ  PORTB
	    GOTO    DIEZ
	    GOTO    REPETIR
DIEZ	    MOVLW   0X0A
	    CPFSEQ  PORTB
	    GOTO    ONCE
	    GOTO    REPETIR
ONCE	    MOVLW   0X0B
	    CPFSEQ  PORTB
	    GOTO    DOCE
	    GOTO    APROBADO
DOCE	    MOVLW   0X0C
	    CPFSEQ  PORTB
	    GOTO    TRECE
	    GOTO    REPETIR
TRECE	    MOVLW   0X0D
	    CPFSEQ  PORTB
	    GOTO    CATORCE
	    GOTO    APROBADO
CATORCE	    MOVLW   0X0E
	    CPFSEQ  PORTB
	    GOTO    QUINCE
	    GOTO    APROBADO
QUINCE	    MOVLW   0X0F
	    CPFSEQ  PORTB
	    GOTO    APAGAR
	    GOTO    APROBADO
	    
APROBADO    BSF	    LATC,RC0
	    GOTO    APAGAR
REPROBADO   BSF	    LATC,RC1
	    GOTO    APAGAR
REPETIR	    BSF	    LATC,RC0
	    BSF	    LATC,RC1
	    GOTO    APAGAR
APAGAR	    BCF	    LATC,RC0
	    BCF	    LATC,RC1
	    GOTO    INICIO
	    END





